<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Javascript\Parser\**" />
    <Content Remove="wwwroot\Javascript\Parser\**" />
    <EmbeddedResource Remove="wwwroot\Javascript\Parser\**" />
    <None Remove="wwwroot\Javascript\Parser\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Javascript\Factories\LineFactory.js" />
    <None Include="wwwroot\Javascript\Factories\ShapeFactory.js" />
    <None Include="wwwroot\Javascript\Models\Line.js" />
    <None Include="wwwroot\Javascript\Services\Builder.js" />
    <None Include="wwwroot\Javascript\Services\LoadDiagram.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
