<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\Javascript\Factories\LineFactory.js" />
    <None Include="wwwroot\Javascript\Factories\ShapeFactory.js" />
    <None Include="wwwroot\Javascript\Models\Line.js" />
    <None Include="wwwroot\Javascript\Models\ShapeType.js" />
    <None Include="wwwroot\Javascript\Parser\Parser.js" />
    <None Include="wwwroot\Javascript\Services\BuildDiagram.js" />
    <None Include="wwwroot\Javascript\Services\LoadDiagram.js" />
  </ItemGroup>

</Project>
