<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Controller\ToolController.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Javascript\Factories\LineFactory.js" />
    <None Include="wwwroot\Javascript\Factories\ShapeFactory.js" />
    <None Include="wwwroot\Javascript\Models\Line.js" />
    <None Include="wwwroot\Javascript\Parser\Parser.js" />
    <None Include="wwwroot\Javascript\Services\Builder.js" />
    <None Include="wwwroot\Javascript\Services\LoadDiagram.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Controller\" />
    <Folder Include="wwwroot\Javascript\Parser\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
